# Generated by Django 3.2 on 2025-05-14 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complain',
            name='status',
            field=models.CharField(choices=[('Initiated', 'Initiated'), ('In Progress', 'In Progress'), ('Resolved', 'Resolved')], default='initiated', max_length=20),
        ),
    ]
